### ISSUE TITLE
bin/setup 'psych gem' error: diff to 'speedrail' default?

### ISSUE THREAD

**Issue by niklasbabel** [ryanckulp/white_bnb#20]
when setting up the project with Ruby 3.3.5, i encountered an issue with the ‘psych' gem. 
the error suggests a mismatch between the installed Ruby version and the system Ruby. (i've probably messed something up) – but when setting up a clean Speedrail (git clone …) this error didn't happen before, just wondering as i've thought it's a direct Speedrail fork. :) 

### Error Message
```
== Starting development server ==
Ignoring psych-5.1.2 because its extensions are not built. Try: gem pristine psych --version 5.1.2
Ignoring stringio-3.1.1 because its extensions are not built. Try: gem pristine stringio --version 3.1.1
Ignoring stringio-3.1.1 because its extensions are not built. Try: gem pristine stringio --version 3.1.1
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require': dlopen(/Users/niklasbabel/.gem/ruby/3.3.5/gems/psych-5.1.2/lib/psych.bundle, 0x0009): Symbol not found: _rb_cObject (LoadError)
  Referenced from: <2063CCB9-C356-31E6-AEDD-53785DD7FE58> /Users/niklasbabel/.gem/ruby/3.3.5/gems/psych-5.1.2/lib/psych.bundle
  Expected in:     <A010185E-A8DB-305A-9A58-231EC4C79CC2> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby - /Users/niklasbabel/.gem/ruby/3.3.5/gems/psych-5.1.2/lib/psych.bundle
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
        from /Users/niklasbabel/.gem/ruby/3.3.5/gems/psych-5.1.2/lib/psych.rb:13:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/homebrew/Cellar/foreman/0.88.1/libexec/gems/foreman-0.88.1/lib/foreman/cli.rb:8:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/homebrew/Cellar/foreman/0.88.1/libexec/gems/foreman-0.88.1/bin/foreman:5:in `<top (required)>'
        from /opt/homebrew/Cellar/foreman/0.88.1/libexec/bin/foreman:23:in `load'
        from /opt/homebrew/Cellar/foreman/0.88.1/libexec/bin/foreman:23:in `<main>'
niklasbabel@NiklasB-MBP white_bnb % gem install psych

Building native extensions. This could take a while...
Successfully installed psych-5.1.2
1 gem installed
niklasbabel@NiklasB-MBP white_bnb % chruby 3.3.5
niklasbabel@NiklasB-MBP white_bnb % ruby -v
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [arm64-darwin24]
niklasbabel@NiklasB-MBP white_bnb % ruby-install --latest
*** DEPRECATION: -L,--latest is deprecated. Please use -U,--update instead.
>>> Downloading latest ruby versions ...
>>> Downloading latest jruby versions ...
>>> Downloading latest truffleruby versions ...
>>> Downloading latest truffleruby-graalvm versions ...
>>> Downloading latest mruby versions ...
Stable ruby versions:
  ruby:
    3.0.7
    3.1.6
    3.2.5
    3.3.5
  jruby:
    9.4.8.0
  truffleruby:
    24.1.0
  truffleruby-graalvm:
    24.1.0
  mruby:
    3.3.0
niklasbabel@NiklasB-MBP white_bnb % ruby -v              
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [arm64-darwin24]
niklasbabel@NiklasB-MBP white_bnb % chruby 3.3.5         
niklasbabel@NiklasB-MBP white_bnb % bin/setup                            
== Installing dependencies ==
The Gemfile's dependencies are satisfied

== Preparing database ==
DEPRECATION WARNING: ActiveSupport::ProxyObject is deprecated and will be removed in Rails 8.0.
Use Ruby's built-in BasicObject instead.
 (called from <main> at /Users/niklasbabel/Documents/code/white_bnb/config/application.rb:7)

== Removing old logs and tempfiles ==
DEPRECATION WARNING: ActiveSupport::ProxyObject is deprecated and will be removed in Rails 8.0.
Use Ruby's built-in BasicObject instead.
 (called from <main> at /Users/niklasbabel/Documents/code/white_bnb/config/application.rb:7)

== Starting development server ==
Ignoring psych-5.1.2 because its extensions are not built. Try: gem pristine psych --version 5.1.2
Ignoring stringio-3.1.1 because its extensions are not built. Try: gem pristine stringio --version 3.1.1
Ignoring stringio-3.1.1 because its extensions are not built. Try: gem pristine stringio --version 3.1.1
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require': dlopen(/Users/niklasbabel/.gem/ruby/3.3.5/gems/psych-5.1.2/lib/psych.bundle, 0x0009): Symbol not found: _rb_cObject (LoadError)
  Referenced from: <7C2F64C1-1691-3B9E-A068-E52EA7D29C38> /Users/niklasbabel/.gem/ruby/3.3.5/gems/psych-5.1.2/lib/psych.bundle
  Expected in:     <A010185E-A8DB-305A-9A58-231EC4C79CC2> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby - /Users/niklasbabel/.gem/ruby/3.3.5/gems/psych-5.1.2/lib/psych.bundle
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
        from /Users/niklasbabel/.gem/ruby/3.3.5/gems/psych-5.1.2/lib/psych.rb:13:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/homebrew/Cellar/foreman/0.88.1/libexec/gems/foreman-0.88.1/lib/foreman/cli.rb:8:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/homebrew/Cellar/foreman/0.88.1/libexec/gems/foreman-0.88.1/bin/foreman:5:in `<top (required)>'
        from /opt/homebrew/Cellar/foreman/0.88.1/libexec/bin/foreman:23:in `load'
        from /opt/homebrew/Cellar/foreman/0.88.1/libexec/bin/foreman:23:in `<main>'
niklasbabel@NiklasB-MBP white_bnb % 
```

### Fix

1. Psych gem install:
2. ensure correct Ruby version is active:
   ```bash
   chruby 3.3.5
   ruby -v
   ```

3. reinstall the `psych` gem:
   ```bash
   gem uninstall psych
   gem install psych
   ```

4. rebuild native extensions:
   ```bash
   gem pristine --all
   ```

5. update Bundler:
   ```bash
   gem install bundler
   bundle update --bundler
   ```

6. reinstall all gems:
   ```bash
   bundle install
   ```

7. reinstall `foreman`
   ```bash
   gem uninstall foreman
   gem install foreman
   ```

8. Check `PATH` to ensure the correct Ruby version is being used:
   ```bash
   which ruby
   which bundle
   ```
   (these should point to paths within your Ruby 3.3.5 installation)

9. optional: might need to reinstall Ruby 3.3.5:
   ```bash
   ruby-install ruby 3.3.5
   ```

try running Rails server again:

```bash
bin/dev
```

**Comment by ryanckulp** [comment]
thanks for sharing the fix. i've had a couple psych issues over the years, usually some growing pain of a dependency that got bumped. in this case, White BNB now diverges from Speedrail a bit because Speedrail is still Rails 7.

bumping Speedrail to Rails 8 soon, then will see if i can replicate this and fix permanently.
